# -*- coding: utf-8 -*-
"""Ricks's Google Colab choart2 practical assessment26/09/26 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5STyy0uSMFV5GpElLJWIjBkDClQvhP5

#Assesment answer booklet theory

***Section A multiple choice***
"""

#Question 1
"B"
#question 2
"c"
#question 3
"B"
#QUESTION 4
"B"
#question 5
"B"
#question 6
"c"
#question 7
"B"
#question 8
"c"
#question 9
"B"
#question 10
"c"
#question 11
"A"
#question 12
"B"
#question 13
"c"
#question 14
"B"
#question 15
"B"
#question 16
"B"
#question 17
"B"
#question 18
"B"
#question 19
"B"
#question 20
"B"

"""**Structured questions**

#Section B

#what is a variable and a value

variables are storage containers for storing values while a value is a piece of data
#examples of valid python variables names

1:school_name = "ed_tech"

2:age = 70


#examples of invalid python_variables


1: 1_summer = "home"

2: int="mabena"


#explain why indentation is important in python

indentation is important because it tells python which block of code belongs together or we could say indentation helps python to indicate a block of code

#example of a comment

**#Man i'm really writting my assesment**
"""



"""**question 2 : code interpretation**"""

scores=[45,67,89,32,76]

total=0
for score in scores:
  total= total+score
  average = total/len(scores)

print(average)

#1 what data type is scores ?
#scores is a list
#2 what does len(scores)return?
#len(scores) will return total number of characters
#3 what is the purpose of the for loop
# the for loop is used for iterating the  sequence
#4 explain the code in simple english
# this block of code prints the average score of student
# for score in scores:
 # total= total+score  #this code will add the total number of score which is zero and our values for score

"""#question 3 debugging

"""

student_name="taririo"
score=int(input("enter score"))

passing_mark = 90
print("tariro")

if score >= 50:
  print("pass")
else:
  print("fail")

"""def calculate_average(scores):
    average = sum(scores) / len(scores)
    return average

student1_scores = [80, 75, 90]
student2_scores = [60, 70, 65]

print(calculate_average(student1_scores))
print(calculate_average(student2_scores))

#Question4:functions
"""

def calculate_average(math,reading,writing):
  total = math + reading + writing
  average = sum(scores)/len(scores)
  return(average)

result= calculate_average(70,80,90)
print("the average score is:", result)

"""#section c

# q1 why is python used in data science
well because  Python has in-built  libraries and functions, which somewhat makes it easier to calculate mathematical problems and to perform analysis.

#q2 explain the purpose of eda
we use eda to analyze and explore datasets and summarize the main characteristics of them.

loading data:we use eda to read raw files like csv files

inspecting data: now here we get to use eda to inspect our data like seeing the size of or shape of our data set

understanding coloumns:  helps us understand if our features are numerical or cartegorical

checking missing values : helps us check if theres any blanksin our data sets

#q3 explain what df.groupby("gender")["math score"].mean()
this line of code groups our data set by gender and the math score and it shows us the mean

it groups coloumns based of gender

shows us the  selected score column how many scores each gender has attained   

and it shows us the calculation performed that will lead us to seeing the mean  and it prints out the expected results

#q4 why is ai not used
because ai will generally show you answers that one hasnt been computed by me as student thus defeating the whole reason of learning and building code muscle memory
"""

