# -*- coding: utf-8 -*-
"""Ricks's Google Colab choart2 practical assessment26/09/26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpGbrNuJ7G6kvLyl8VxU4L5cEMsDkD6B

#Data science cohort 2 practical kaggle
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

#for charts to show
# %matplotlib inline

Students_Performance = pd.read_csv("/content/StudentsPerformance.csv")
Students_Performance

Students_Performance.head(5)

Students_Performance.tail()

Students_Performance.describe()

Students_Performance.shape

Students_Performance.dtypes

Students_Performance.columns

Students_Performance.info()

Student_Performance = (df.isnull().sum() / len(df)) * 100
Student_Performance

Students_Preformance= df.duplicated().sum()
Students_Performance

Students_Performance= df.select_dtypes(include=["object"]).columns
Students_Performance

Students_Preformance = df["total_score"]= df["math score"] + df["reading score"] + df["writing score"]